-- ============================================================
-- Roam-Blón · System Evaluation Survey
-- Run once in Supabase → SQL Editor.
-- Stores the Likert-scale evaluation answers submitted by
-- tourists (the checklist form above "Experience More"), and
-- feeds the "Evaluations" section in the admin dashboard.
-- ============================================================

-- 1. evaluations table — one row per completed survey
create table if not exists public.evaluations (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  age text,
  gender text,
  nationality text,
  -- Likert scores 1-5 for each sub-characteristic
  effectiveness integer,
  efficiency integer,
  usefulness integer,
  trust integer,
  pleasure integer,
  comfort integer,
  economic_risk integer,
  health_safety_risk integer,
  environmental_risk integer,
  context_completeness integer,
  flexibility integer,
  created_at timestamptz default now()
);

create index if not exists evaluations_created_idx on public.evaluations (created_at desc);

-- 2. Row Level Security — allow anonymous visitors to submit
alter table public.evaluations enable row level security;

-- Anyone (anon) may insert a response
create policy "allow anon evaluation insert"
  on public.evaluations for insert
  with check (true);

-- Admins may read all responses
create policy "allow anon evaluation select"
  on public.evaluations for select
  using (true);
