-- ============================================================
-- Roam-Blón · Scan Nationality Tracking
-- Run once in Supabase → SQL Editor.
-- Creates the qr_scans table (with nationality) so every QR scan
-- can record whether the visitor is Local or Foreign, and that data
-- feeds the "Top Nationalities" panel in the admin dashboard.
-- ============================================================

-- 1. qr_scans table — one row per QR scan
create table if not exists public.qr_scans (
  id bigint generated by default as identity primary key,
  item_type text,
  item_id text,
  item_name text,
  visitor_type text default 'local',      -- 'local' | 'foreign'
  nationality text,                        -- nationality or 'Local'/'Foreign'
  scanned_at timestamptz default now(),
  created_at timestamptz default now()
);

-- Index for fast top-nationality aggregation
create index if not exists qr_scans_nationality_idx on public.qr_scans (nationality);
create index if not exists qr_scans_scanned_at_idx on public.qr_scans (scanned_at desc);

-- 2. Row Level Security — allow anonymous visitors to insert their own scan
alter table public.qr_scans enable row level security;

-- Anyone (anon) may insert a scan record
create policy "allow anon scan insert"
  on public.qr_scans for insert
  with check (true);

-- Admins may read all scans (scans are returned via service-role API route anyway)
create policy "allow anon scan select"
  on public.qr_scans for select
  using (true);

-- ============================================================
-- OPTIONAL VIEW: Top Nationalities across tourists + scans
-- Combines registered tourists and anonymous scan visitors so the
-- dashboard's Top Nationalities panel reflects both sources.
-- ============================================================
create or replace view public.top_nationalities as
select nationality, count(*) as count
from (
  select nationality from public.tourists where nationality is not null
  union all
  select nationality from public.qr_scans where nationality is not null
) all_visitors
group by nationality
order by count desc;